### ISSUE TITLE
Problem when importing 

### ISSUE THREAD

**Issue by aloreggia** [vlbthambawita/singan-seg-polyp#1]
Hi,
I have just installed the package using pip install, but when I try to run the code or import singan_polyp_aug I get the following error:
    from singan_polyp_aug.config import get_arguments
ModuleNotFoundError: No module named 'singan_polyp_aug'

Any idea how to fix the problem?

Many thanks
Andrea

**Comment by erdem-ezer** [comment]
Hi; I got the same error. 
After pypi package installation with "pip install singan_seg_polyp" command

"from singan_seg_polyp import generate_data, prepare_requirements"
gives ModuleNotFoundError: No module named 'singan_polyp_aug'  error.

**Comment by vlbthambawita** [comment]
Hi both, Sorry for the late replies in here. I have fixed this issue in the new version. Can you try to reinstall the package and retry ?
